import type { Metadata } from "next";
import { NavigationMenuDemo } from "../components/ui/layout/HeaderHome";
import Image from "next/image";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
<<<<<<< Updated upstream
import { NavigationMenuDemo } from "./component/layout/HeaderHome";
=======
import { IoMdSearch } from "react-icons/io";
import { FaRegUser } from "react-icons/fa6";
import { AiOutlineShoppingCart } from "react-icons/ai";

>>>>>>> Stashed changes

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fn" dir="rtl" className="h-screen w-full items-center">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
<<<<<<< Updated upstream
<<<<<<< Updated upstream
        <div>
          <NavigationMenuDemo/>
=======
        <div className="bg-sky-950">
        
>>>>>>> Stashed changes
=======
        <div className="mx-auto bg-[#C5E0B7] w-full h-20 items-center flex flex-row justify-between px-14 pt-2 pb-1.5">
          <div className="flex flex-row opacity-80 items-center justify-start ">
            <button className="mx-1">
              <IoMdSearch className="size-5"/>
            </button>
            <button className="mx-1">
              <FaRegUser className="size-4"/>
            </button>
            <button className="mx-2">
              <AiOutlineShoppingCart className="size-4"/>
            </button>
          </div>
          <NavigationMenuDemo />
          <img src="bioaqoua.avif" alt="Bioaqoua" className="w-36" />

>>>>>>> Stashed changes
        </div>
        {children}
      </body>
    </html>
  );
}
