import type { Metadata } from "next";
import "../globals.css";
import ReduxProvider from "@/lib/reduxProvider";



export const metadata: Metadata = {
  title: "Payment",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <ReduxProvider>
      <html lang="fn" dir="rtl" className="h-fit w-full items-center dark">
        <head>
          <meta charSet="utf-8" />
          <link href="../style.css" rel="stylesheet"></link>
        </head>

        <body className=" bg-white mt-32 mx-16">
          {/* <Header /> */}
          
          {children}
          
        </body>
      </html>
    </ReduxProvider>
  );
}
