import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/layout/Header";
import Footer from "@/components/layout/footer";
import ReduxProvider from "@/lib/reduxProvider";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {



  return (
    <ReduxProvider>
      <html lang="fn" dir="rtl" className=" w-full items-center dark">
        <head>
          <meta charSet="utf-8" />
          <link href="../style.css" rel="stylesheet"></link>
        </head>

        <body className=" bg-gradient-to-bl from-AquaHaze from-4% via-LinenBeige to-CashmereBlush 
         transition-all duration-5 bg-fixed flex flex-col justufy-center items-center">
          <Header />
          
          {children}
          <div className="flex flee-col text-sm md:mx-auto md:w-[65%] justify-between 
        py-10 md:gap-10 text-gray-700 font-light ">
            <Footer />
            <div>
              <img src="http://localhost:8000/uploads/image-1738349698115-546474799.avif" alt="Bioaqoua" className="md:w-40 md:mr-24 w-52" />
            </div>
          </div>
        </body>
      </html>
    </ReduxProvider>
  );
}
